### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by wootwoot1234** [Wtower/ng-gentelella#22]
Hello,

Thanks for putting this together, I can't wait to use it.  I get the following when I try to install it using npm.

> Tom$ npm install -S ng-gentelella
> npm WARN saveError ENOENT: no such file or directory, open '/Users/Tom/Downloads/ng-gentelella/package.json'
> /Users/Tom/Downloads/ng-gentelella
> └─┬ ng-gentelella@0.2.6
>   ├── angular@1.6.2
>   ├── angular-animate@1.6.2
>   ├── angular-resource@1.6.2
>   ├── angular-route@1.6.2
>   ├── angular-sanitize@1.6.2
>   ├── bootstrap@3.3.7
>   ├── font-awesome@4.7.0
>   ├── gentelella@1.3.0
>   ├── jquery@2.2.4
>   └── ng-file-upload@12.2.13
> 
> npm WARN enoent ENOENT: no such file or directory, open '/Users/Tom/Downloads/ng-gentelella/package.json'
> npm WARN ng-gentelella No description
> npm WARN ng-gentelella No repository field.
> npm WARN ng-gentelella No README data
> npm WARN ng-gentelella No license field.

**Comment by Wtower** [comment]
Hi,

Thanks for your kind words and for the time you took to fill this issue in.

Could you please let me know of node and npm version?

**Comment by wootwoot1234** [comment]
> Tom$ npm -v
> 3.10.3

**Comment by Wtower** [comment]
And the node version?

**Comment by wootwoot1234** [comment]
Ha.  Oops.  You meant this:

> Tom$ node -v
> v6.6.0

**Comment by Wtower** [comment]
Thanks. Unfortunately I am not able to reproduce this:

```
gkarak@rodope ~/w/tests> nvm install 6.6.0
######################################################################## 100,0%
Checksums empty
Now using node v6.6.0
gkarak@rodope ~/w/tests> npm -v
3.10.3
gkarak@rodope ~/w/tests> npm install ng-gentelella
/home/gkarak/workspace/tests
└─┬ ng-gentelella@0.2.6 
  ├── angular@1.6.2 
  ├── angular-animate@1.6.2 
  ├── angular-resource@1.6.2 
  ├── angular-route@1.6.2 
  ├── angular-sanitize@1.6.2 
  ├── bootstrap@3.3.7 
  ├── font-awesome@4.7.0 
  ├── gentelella@1.3.0 
  ├── jquery@2.2.4 
  └── ng-file-upload@12.2.13 

npm WARN enoent ENOENT: no such file or directory, open '/home/gkarak/workspace/tests/package.json'
npm WARN tests No description
npm WARN tests No repository field.
npm WARN tests No README data
npm WARN tests No license field.
gkarak@rodope ~/w/tests> 
```

In any case, I would recommend you to update your npm to latest version and retry:

    npm install -g npm

**Comment by Wtower** [comment]
Now that I see your initial post again, it seems that the package is indeed installed. The last `WARN` messages are because there is no `package.json` file in the current directory.

Could it be this?

**Comment by wootwoot1234** [comment]
Yeah, I guess I'm seeing the same thing you are.  Now if I look in the folder where I ran `npm install -S ng-gentelella` all I see is the node_modules folder and nothing else.  What else do I need to do to get started?

**Comment by Wtower** [comment]
That's right. You would need to drop this module in your web site. Then you would need to create an Angular application for your administration interface that would use the ng-gentella module.

If you do not have a web site yet, you need to consider which stack you are going to use. I have created a yeoman generator for initialising the necessary boilerplate files for MEAN stack. This also uses the present ng-gentelella module. The generator is [generator-makrina][1].

If you do not wish to use it, or you have got already a web site code: You can browse in the generator template files to take a look at how the code is structured:

- The [basic generated project files][2]
- The [generated Angular application for the admin UI][3]
- A [sample service Angular module][4] to communicate with your REST API
- A [sample list Angular component][5] to present your data in a table
- A [sample detail Angular component][6] to present a form

All of the above use the ng-gentelella module and are based on the [Angular tutorial][7] a lot, which might also help.

I hope this was helpful.

[1]: https://github.com/Wtower/generator-makrina
[2]: https://github.com/Wtower/generator-makrina/tree/master/generators/app/templates
[3]: https://github.com/Wtower/generator-makrina/tree/master/generators/angular-app/templates
[4]: https://github.com/Wtower/generator-makrina/tree/master/generators/angular-core-service/templates
[5]: https://github.com/Wtower/generator-makrina/tree/master/generators/angular-component-list/templates
[6]: https://github.com/Wtower/generator-makrina/tree/master/generators/angular-component-detail/templates
[7]: https://docs.angularjs.org/tutorial

**Comment by SehgalDivij** [comment]
Added any directives for sidebar?
