### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by JeremyKeusters** [Wtower/ng-gentelella#23]
Hello,

First of all, thank you for this nice project. I'm trying to run this dashboard locally, but when I try npm start, it says: `missing script: start`

Is this normal? Is there another way to run this?

Thanks!

**Comment by Wtower** [comment]
Hi, thanks for your kind words and the time you took to fill this in.

Have you read the [documentation][1] about how to install it? There is no startup script, you have to include the built files and use the angular components into your project.

Also take a look at https://github.com/Wtower/ng-gentelella/issues/22#issuecomment-283751270 .

[1]: http://ng-gentelella.readthedocs.io/en/latest/installation.html
